### ISSUE TITLE
minimal walltime

### ISSUE THREAD

**Issue by matthieu637** [lpouillo/Funk#46]
It would be great if the option -w was not mandatory and completed with another option to specify the minimal walltime wanted. 

The maximum walltime could be computed by outofchart and the current available resources.

So depending of each site, the walltime could be different.

**Comment by lpouillo** [comment]
Hi Matthieu, 

To compute the maximum walltime, I can use the Charter module 
http://execo.gforge.inria.fr/doc/latest-stable/execo_g5k.html#grid5000-charter

I am not sure to understand your wish. If now walltime is specified, it simply use default oarsub walltime.

Can you give me better explanation of the feature you want ?

Thanks a lot.

**Comment by matthieu637** [comment]
Here an example : 
I know that my experience needs at least 3 hours to be complete (this will be the minimum walltime), however it is still good to reserve more than 3 hours because I had a lot of experiences to finished.

There is : 
- 20 nodes available at Reims between 8:59 and 18:59.
- 12 nodes available at Lyon between 8:59 and 16:00.
- 6 nodes available at Nancy between 8:59 and 10:00.
- 20 nodes available at Rennes between 8:59 and 20:00.

I know that I can reverse the following cumulated hours for one day:
- 1872h for Reims (and there is 24 cpu/node)
- 704h for Lyon (and there is 12 cpu/node)
- 4736h for Rennes  (and there is 16 cpu/node)
(The culumated hours have been taken from outofchart)

Thus with one funk command I would like to reserve :
- 7 nodes at Reims between 8:59 and 18:59. (1872 h / 24 cpu / 10 hours = 7 nodes )
- 8 nodes at Lyon between 8:59 and 16:00. (704 h / 12 cpu / 7 hours = 8 nodes)
- 0 nodes at Nancy because of the minimal walltime
- 20 nodes at Rennes between 8:59 and 18:59 ( 4736h / 16 cpu / 10 hours = 30 nodes so there is but there is not enough ressources )

As you can see the ending time is not the same on all clusters. Notice also that Rennes reservation finished at 18:59 and not 20:00 (because of the charter).

I hope it is more clear. I don't know if it possible with python (in particular I don't know if you can access to the cpu/node ).

**Comment by lpouillo** [comment]
Hi Matthieu,

everything is possible but I will probably not have time to add this feature.

However, you can consider two solutions : 
* create a pull request
* switch to the power of execo_engine.

Actually, funk is a simple helper to manage multi-sites reservations which is based on [Execo](http://execo.gforge.inria.fr). This python package provides a lot of functions to help you in your g5k experiments :
* [execo core] (http://execo.gforge.inria.fr/doc/latest-stable/execo.html), that provides very powerfull functions to manage remote unix processes
* execo_g5k, especially [planning] (http://execo.gforge.inria.fr/doc/latest-stable/execo_g5k.html) and [charter] (execo.gforge.inria.fr/doc/latest-stable/execo_g5k.html) features that allow you to automatize your complex reservations, and [api_utils] (http://execo.gforge.inria.fr/doc/latest-stable/execo_g5k.html#module-execo_g5k.api_utils)
* [execo_engine] (http://execo.gforge.inria.fr/doc/latest-stable/execo_engine.html) that provides very interesting functions for ParamSweeping, which seems to be the case for you as you have a lot of experiments to run.

If you are not familiar with Python, you can have a look at the examples on the [execo documentation] (http://execo.gforge.inria.fr/doc/latest-stable/userguide.html) as well as on the Grid'5000 wiki that provides a simple [tutorial] (https://www.grid5000.fr/mediawiki/index.php/Execo_Practical_Session) and the [Github code repository] (https://github.com/lpouillo/execo-g5k-tools).

Let me know if this can help you.

Regards,

Laurent

**Comment by lpouillo** [comment]
As this feature is really specific and as I am leaving g5k, I close the issue. 

Matthieu, please have a look to the previous comment. 
There will be a tutorial session at Grenoble 2016 G5K School.

Sorry.
