### ISSUE TITLE
besteffort reservation failed

### ISSUE THREAD

**Issue by matthieu637** [lpouillo/Funk#50]
Hello,
Here is a small improvement.

Consider the following funk command (reserve 2 nodes on sophia during 4 hours) :
```
funk -m free -r "sophia:2" -w "4:00:00" -o "-t deploy -t besteffort" -q "besteffort" -y
```
It will results in the following oarsub command
```
oarsub -t deploy -t besteffort -l "nodes=2,walltime=4:0:0" -q "besteffort" -r "2015-11-30 14:19:15" -n "FUNK" "sleep 31536000"
```
However because of the -r argument, it will be rejected
```
Admission Rule ERROR : [ADMISSION RULE] Error: a job cannot both be of type besteffort and be a reservation.
```

Could funk detects the queue and if it's besteffort remove the -r argument ?

**Comment by lpouillo** [comment]
Hello,

Funk was initially developed intended to help users in performing large scale and multi-sites RESERVATION.

In the original version of execo_g5k.planning which is used by funk to gather and treat site planning, best-effort jobs were simply considered. However, we recently add an option is this submodule to be able to orchestrate best-effort campaigns and so to take into account.

As you seem to be an advanced g5k user, I advise you to try to develop your an execo_engine to manage finely your campaign.

Example of methods : 
import execo_g5k

  def get_immediately_available_nodes(list_of_clusters, walltime, ignore_besteffort = True):
      planning = execo_g5k.get_planning(list_of_clusters, ignore_besteffort = ignore_besteffort)
      slots = execo_g5k.compute_slots(planning, walltime)
      wanted = { cluster: 0 for cluster in list_of_clusters }
      start_date, end_date, resources = slots[0]
      actual_resources = { resource: n_nodes
                         for resource, n_nodes in resources.iteritems()
                         if resource in list_of_clusters and n_nodes > 0 }
      return start_date, end_date, actual_resources

  def submit_all_available_best_effort(list_of_clusters, walltime):
      start_date, end_date, resources = get_immediately_available_nodes(list_of_clusters, walltime,  ignore_besteffort = False)
      job_specs = execo_g5k.get_jobs_specs(resources)
      for j,f in job_specs:
          j.job_type = "besteffort"
      jobs = execo_g5k.oarsub(job_specs)
      return jobs

**Comment by matthieu637** [comment]
Thanks for your help. I'll look at it.

**Comment by lpouillo** [comment]
Some more g5k examples can be found here.
http://execo.gforge.inria.fr/doc/latest-stable/userguide.html#execo-g5k
